var palabras = {
	"positivo":{
		"a":[
			"a la vista","a montones","a toda prueba","abiertamente","abogado","abogó","abrazo",
			"absoluta","absolutamente","absorbe","absorbente","absorto","abunda","abundan",
			"abundancia","abundando","abundante","acariciado","accesible","acción","acelerado",
			"aceptable","aceptación","aceptada","aceptar","acero","aclamación","aclamada","aclara",
			"acogedor","acomodación","acomodado","acomodar","acomodaticia","actitud","actitud positiva",
			"activar","activo","actualidad","actualizable","actualización","actualizado","acuerdan",
			"adaptabilidad","adaptación","adecuada","adecuadamente","adecuado","adelanta","adelantamiento",
			"adelantar","adelante","además","adjudicado","admirablemente","admiración","admirador",
			"admirativamente","adorable","adoración","adorado","adorador","adorar","adulación","adulador",
			"adular","afable","afablemente","afán","afectación","afecto","afectuosa","afectuosamente",
			"afiladas","afinidad","afirmación","afirmar","afirmativa","afluencia","afluente",
			"afortunadamente","afortunado","agilidad","ágilmente","agraciada","agraciado","agrada",
			"agradabilidad","agradable","agradablemente","agradecido","agradecimiento","agradecimientos",
			"agrado","agua","ahorro","ahorros","aire","ajustable","al instante","alabando","alcance",
			"alcanzable","alcanzar","alegre","alegremente","alegre-voluntad","alegría","alegrías",
			"alentado","alentador","alentar","alerta","alimentación","alimentados","alimentos","alineados",
			"alisa","aliviado","aliviar","alivio","alivió","allá-fabuloso","alma","alma de la fiesta",
			"alojamiento","alta calidad","alta civismo","alta energía","altruismo","altruista","amabilidad",
			"amable","amablemente","amado","amanecer","amante","amar","amar-aceptación","amarillo",
			"amar-sentimientos","ambición","ambiciosamente","ambicioso","amenidad","amenizada",
			"amigable para los niños","amigablemente","amigo","amistad","amistosa","amistoso","amor",
			"amor propio","amores","ampliamente","amplio","añadir","ángel","angélica","anhelamos",
			"animación","animada","animado","animando","animar","ánimo","ánimo para la vida","anticipación",
			"apacible","apalancamiento","apasionada","apasionado","apelación","apenas","apertura",
			"aplauden","apoteosis","apoyo","aprecia","apreciable","apreciada","apreciando","apreciar",
			"aprecio","aprender","aprendizaje","aprobación","aprobar","apropiado","aprovechamiento","apta",
			"ardiente","ardientemente","armonía","armoniosa","armoniosamente","arrollador","articulo",
			"asegurados","aseguramiento","asegurar","asequible","asequibles","a-ser-conocido","asertividad",
			"asertivo","asombra","asombrado","asombrar","asombro","asombrosamente","asombroso","asombrosos",
			"aspiración","aspiraciones","astronómico","astutamente","asunción de riesgos","atemorizado",
			"atención","atento","atestiguar","atormentar","atracción","atracción sexual","atractiva",
			"atractivo","atraídos","atrevidamente","aturdido","audacia","audaz","auge","auspicioso",
			"autenticidad","auténtico","auto cuidado","auto-amabilidad","auto-compasión",
			"autodeterminación","auto-enhacement","autoestima","autoexpresión","autónoma","autonomía",
			"auto-perdón","autoritario","autorizado","autosuficiencia","autosuficientes","avance","avances",
			"avanzada","aventajado","aventuras","aventurero","ávidamente","avivar","ayuda","ayudado",
			"ayudando"
		],
		"b":[
			"bajo costo","bajo precio","barato","barrido","basta","bastado","bastante","beatificar",
			"beatitud","bella","bellamente","belleza","bendición","bendita","beneficiario","beneficio",
			"beneficios","beneficiosamente","beneficioso","benéfico","benevolencia","benévolo","beso",
			"bien","bien conectado","bien conocido","bien considerado","bien educado","bien equilibrada",
			"bien establecido-","bien gestionada","bien hecho","bien informado","bien intencionado",
			"bien parecido","bien recibido","bien redondeado","bien retroiluminado","bienestar",
			"bienquerientes","bienvenidos","biofilia","bondad","bondad amorosa","bonitamente","bonos",
			"botín","boyante","brilla","brillante","brillo","brillos","broma","buen aspecto","buena salud",
			"buena voluntad","bueno","burlar"
		],
		"c":[
			"caballería","caballerosidad","cables","cachorros","calentador","calidad","caliente",
			"calificado","calificar","calma","calor","cambio","capacidad","capaz","caridad","cariño",
			"cariñoso","carisma","carismático","cautivados","cautivar","cautivó","ceder","cegamiento",
			"celante","celebración","celebrada","celebradora","celebrando","celebrar","celestial","celo",
			"centrado","cercanía","certeza","chispa","chispas","chistosa","chistoso","cielo","ciertamente",
			"cierto","citas","civilizar","civismo","clara","claramente","claridad","claro","clase",
			"clásico","coherencia","coherente","cohesiva","colaboración","colorido","confortablemente",
			"como","cómodamente","cómodo","compacta","compañerismo","compartir","compasión","compasivo",
			"competencia","competente","competitiva","complaciente","complementado","complementaria",
			"complemento","complementos","comprensible","comprensivo","comprobado","comprometido",
			"compromiso","comunicación","comunidad","comunión","con confianza","con dulzura",
			"con entusiasmo","con éxito","con gusto","con justicia","con mejores resultados",
			"con mucho gusto","con tenacidad","conceder","concentración","conciencia","conciliador",
			"conciliar","conciso","conducir","conectividad","conexión","confiabilidad","confiable",
			"confiablemente","confiado","confianza","confiar","confirmó","confort","congratulatoria",
			"congruencia","conmovedoramente","conocimiento","conquistar","consciente","consideración",
			"considerado","consistencia","consistente","consistentemente","consolidación","constancia",
			"constructivo","consuelo","consumado","contenido","contentamiento","contento","continua",
			"continuidad","contraataques","contribución","conveniencia","conveniente","convenientemente",
			"convicción","convincente","convincentemente","cooperación","cooperativa","cooperativamente",
			"coraje","corazón","corazón amable","corazón de león","cordialidad","cordialmente",
			"correctamente","correcto","corteje","cortés","cortesía","cosquillas","costo de ahorro",
			"crear","creatividad","creativo","crecer","crecimiento","crecimiento personal","creíble",
			"cuidado","cuidadosamente","cuidando","cumple","cumplida","cumplido","cumplimiento","cumplir",
			"curiosamente","curiosidad","curioso"
		],
		"d":[
			"dios","dando","dar","posición","ademanes",
			"abierto","decisión","lujo","crecimiento",
			"audible","primera","categoría","clase","rápido","crecimiento",
			"reina","corazón","fácil","deber","decencia","decente","decisivo",
			"dedicado","defectos","defender","defensor","defensores","deferencia","deleitarse",
			"delicadeza","delicado","delicias","deliciosa","deliciosamente","deliciosas","delicioso",
			"deportivo","derecho","derrame","derrota","derrotado","derrotando","derrotas","descansamos",
			"descaradamente","descubrimiento","deseable","deseando","deseo","desinterés","deslumbrado",
			"desmontable","despejado","despertó","despierte","despliegue","desprendimiento",
			"despreocupación","despreocupada","destacar","destino","destreza","desvergonzado",
			"determinación","deuda","devoción","dinero","devoto","devuelto","dichosamente",
			"dichoso","diestramente","diestro","respirar","digna","dignidad","dignificar",
			"digno","diligencia","diligente","diligentemente","diluyente","dinámica","dios","manda",
			"mío","diosa","diplomática","dirección","disciplina","discreción","disfruta",
			"disfruta","disfrutado","disfrutar","disfrute","disponible","dispuestos","distinción",
			"distinguido","distintivo","diversidad","diversificada","divertida","divertido","divina",
			"divinamente","divino","dócil","domina","dominado","dominar","dorado","dotado","dulce",
			"dulzura","duradero"
		],
		"e":[
			"eclipsar","eclipsó","económica","económico","ecosofía","ecuánime","ecuanimidad","edificar",
			"educación","educada","educado","educar","efectivamente","eficacia","eficaz","eficiencia",
			"energética","eficiente","efusivamente","efusividad","efusivo","egocéntrico",
			"ejemplar","elástico","elección","elegancia","elegante","elevación",
			"elevada","elevando","elocuente","elocuentemente","elogiar","elogio","elogiosamente",
			"embarazada","embelesado","embellecer","eminencia","eminente","emoción","emocionada",
			"emocionado","emocionado-anticipación","emocionante","emocionantemente","emociones",
			"empatía","empatizar","empoderamiento","emprendedor","en","apoyo","busca",
			"punto","vivo","enamorado","encantado","encantador","encantadoramente",
			"encanto","encargado","encendedor","encomiable","enderezar","endulzar","energética",
			"energía","positiva","enfático","engatusar","enhorabuena","ennoblecer","enorme",
			"enriquecimiento","ensalzar","enseñar","entender","entendido","entendimiento","entrañable",
			"entretenimiento","entretiene","entusiasmar","entusiasmo","entusiasta","envalentonar",
			"envidia","envidiable","envidiablemente","envidioso","epifanía","equidad","equilibrado",
			"equipo","equitativa","equitativo","ergonómico","erudito","alentador","escénico",
			"escuchar","escultural","esencia","esfuerzo","esmerado","espacio","especial","especializado",
			"espectacular","espectacularmente","esperanza","espíritu","espiritual","espléndidamente",
			"esplendor","espontánea","espontaneidad","estabilidad","estabilizar","estable","estacionario",
			"mental","estelar","estilo","estimula","estimulación","estimulada","estimulante",
			"estimular","estrella","estrellazo","estudio","estudioso","estupefacto",
			"estupendamente","estupendo","etéreo","eterna","eterno","ética","eudemonismo","eudemonista",
			"euforia","eufóricamente","eufórico","eutonía","evaluativo","evocador","exactamente",
			"exaltación","exaltadamente","exaltado","exaltando","examen","exceder","excelencia",
			"excelente","excelentemente","excepcional","excesivamente","excita","excitar","exclusivo",
			"existencia","exitazos","éxito","éxitos","exitosa","exonerar","expansivo","experiencia",
			"expertamente","exploración","explosivos","expresando","expresividad","expreso",
			"exquisitamente","exquisito","extasiar","éxtasis","extático","extraordinaria",
			"extraordinariamente","extrovertida","exuberancia","exuberante","exuberantemente",
			"exultación","exultante"
		],
		"f":[
			"fabulosamente","fabuloso","fácil","usar","hablar",
			"facilidad","facilita","facilitar","fácilmente","factible",
			"factiblemente","familia","famosamente","famoso","fantástico","fascinación","fascinado",
			"fascinante","fascinantemente","favor","favorecida","favorito","fe","felicidad","felicidades",
			"felicita","felicitar","feliz","felpa","fenomenal","fenomenalmente","feria","fértil",
			"ferviente","fervientemente","fervorosamente","fervoroso","festividad","festivo","fidelidad",
			"fiel","fielmente","finalmente","fino","firme","firmemente","firmeza","flexibilidad","flor",
			"floreciente","flotabilidad","flujo","fluye","fomento","formalmente","fortaleza",
			"fortuitamente","fortuito","fragante","fraternal","fresco","frescura","frivolidad",
			"fructífero","frugalidad","fuerte","fuerza","paz","futurista","futuro"
		],
		"g":[
			"gallardamente","ganable","ganado","ganador","ganadores","ganancias","ganando","ganar",
			"ganga","garantía","garantías","garbo","gatitos","generar","generosamente","generosidad",
			"generoso","genial","genuino","gigantesco","glamour","gloria","glorificar","gloriosa",
			"gloriosamente","gomoso","gozosamente","gracia","gracias","graciosamente","gran",
			"gran capacidad","grande","grandeza","grandiosidad","granizo","gratamente","gratifica",
			"gratificación","gratificante","gratificantemente","gratis","gratitud","guau","guía",
			"gustado","gusto","gustos"
		],
		"h":[
			"hábil","habilidad","habilitado","habilitar","hábilmente","hace señas","hace suya","hacer",
			"hacer señas","hacerse querer por","haciendo la diferencia","halagadoramente","halagar",
			"hermosa","hermosamente","hermoso","hermosura","héroe","héroes","heroica","heroicidad",
			"heroína","heroísmo","hidalgo","hilarante","hipnotiza","hipnotizado","hipnotizante",
			"hipnotizar","hizo señas","hola","holística","homenaje","honestidad","honesto","honra",
			"honrado","hospitalario","hospitalidad","humano","humildad","humilde","humor",
			"humorísticamente"
		],
		"i":[
			"idealismo","idealizar","idílica","idolatrado","idolatrar","igualdad","ilimitado",
			"iluminación","iluminado","iluminar","ilustre","imaginación","imaginativa","impaciencia",
			"impaciente","imparable","imparcial","imparcialidad","imparcialmente","impávido","impecable",
			"impecablemente","impertinencia","imponencia","imponente","importante","importar",
			"impresiona","impresionante","impresionantemente","inafectado","inatacable","inclusión",
			"incomparable","incondicional","incondicionalmente","inconsútil","increíble","increíblemente",
			"incuestionable","indemne","independencia","indiscutible","indiscutiblemente",
			"individualizado","indudable","indulgente","inefable","inequívocamente","inequívoco",
			"inestimable","inestimablemente","infalibilidad","infalible","infaliblemente","infinito",
			"influencia","influyentes","ingenio","ingeniosamente","ingenioso","ingenuamente","ingenuo",
			"inicio","inigualable","inmaculada","inmejorable","inmenso","innovación","innovador","innovar",
			"inocente","inocuo","inolvidable","inquebrantable","inquisitivo","inspiración","inspirado",
			"instalaciones","instructivo","integrado","integral","integridad",
			"inteligencia","inteligente","inteligible","intención","intensidad","interés","interesado",
			"interesante","intereses","intimidad","íntimo","intriga","intrigado","intrigante",
			"intrincado","intuitividad","intuitivo","invalorable","invencible","invencibles","inventiva",
			"invertir","investigación","inviolado","involucrar","iridiscente","ir-la-extra-milla",
			"irreal","irreprensible","irreprochable"
		],
		"j":[
			"jengibre","joven","jovialidad","jubilación","jubilosa","jubilosamente",
			"jubiloso","juego","juguetona","juguetónamente","juicioso","justicia","justo","juvenil",
			"juventud"
		],
		"l":[
			"laudablemente","leal","lealtad","legal","legendario","legible","legítimamente",
			"legítimo","levantamiento","ley","liberación","liberado","liberar","libertad","libertades",
			"líder","liderazgo","limpia","limpiador","limpieza","lindo","lírica","lisa","lisonjeramente",
			"listo","llamativa","llamativo","loable","lógica","lógico","lograr","logro",
			"logros","longevidad","lucha","lúcidamente","lúcido",
			"lucrativas","lucrativo","lujosamente","lujoso","lujuriante","luminoso","lustre","lustroso",
			"luto","luz"
		],
		"m":[
			"maduramente","madurez","maduro","maestría","maestro","mágico","magistral","magistralmente",
			"magnánimamente","magnanimidad","magnánimo","magnifica","magnífica","magníficamente",
			"magnificencia","magnífico","majestad","manejable","maniobrable","manos abajo","mantenga",
			"maravillaron","maravillas","maravillosa","maravillosamente","maravilloso","más",
			"afortunado","agradable","aguda","barato","bonito","caliente",
			"conocido","duro","espacioso","fácil","feliz","firme","firmes",
			"fresco","frescos","inteligente","práctico","rápido","resistente",
			"resistentes","suave","suerte","vendido","máxima","meditación",
			"mejor","mejora","mejorada","mejorado","mejorar",
			"mejoras","melifluo","meliorismo",
			"melocotón","memorable","mentalidad",
			"merecedor","merecidamente","mérito","meritorios","meticulosamente","meticuloso","milagro",
			"milagros","milagrosa","milagrosamente","misericordia","misericordioso","moda","moderno",
			"modestia","modesto","monumentalmente","moralidad","motivación","motivado","motivar",
			"movido","movimiento","muchos","muerto en","multiusos","mundialmente","mutualidad",
			"muy",
		],
		"n":[
			"nacimiento","naturaleza","navegable","neotenia","niza",
			"resistente","noble","notable","notablemente","novedad",
			"nuevo","nutritiva"
		],
		"o":[
			"obediente","obra","obsceno","obsesión","obtenible",
			"omnipotencia","oportunidad","oportuno","óptima","optimismo","optimista","optimizado",
			"optimizar","opulento","orden","ordenado","organización","orgásmico","orgullo","orgulloso",
			"orientación","originalidad","oro","ostentoso"
		],
		"p":[
			"paciencia","paciente","pacientemente","pacífica","pacifico","pacífico","pacto","pagar",
			"paloma","panacea","panorámica","panqueques","paradisíaco","participación","participe",
			"partidario","pasión","pasmosamente","pasmoso","patriota","patriótica","paz",
			"pendientes","pensativo","perdón","perdonar",
			"perfección","perfeccionamiento","perfectamente","perfecto","permitida","permitiendo",
			"permitir","perseverad","perseverancia","persistencia","personajes","personalizado",
			"perspicacia","perspicazmente","persuasión","pertenecer","pertenencia","piadosa",
			"piadosamente","picante","piedad","pintoresco","pionero","placer",
			"placeres","plenitud","poder","poderosamente","poderoso","poética","poetizar","favor",
			"portátil","positivamente","positivo","positivos",
			"positivos-circunstancias","positivos-creencias","positivos-eventos","potencia","potente",
			"práctico","precioso","precisa","precisamente","precisión","preeminente","preferentemente",
			"preferible","preferido","prefiere","prefiriendo","premio","premios","preparación",
			"preponderancia","presencia","preservación","presteza","prestigio","previsión",
			"principios","privacidad","privilegiada","privilegio",
			"proactiva","proactividad","probabilidades","probar","pródigamente","prodigiosa",
			"prodigiosamente","productiva","productivo","profunda","profundamente","profusión","profuso",
			"progresivo","progreso","promesa","promesas","prometedora","prometida","prominente",
			"promotor","prontitud","propiciamente","propicio","propósito","próspera","prosperidad",
			"próspero","protagonismo","protección","proteja","prudencia","prudente","prueba","pujante",
			"pulido","puntual","puntualidad","puntualmente"
		],
		"q":[
			"querido","quiescente"
		],
		"r":[
			"racional","racionalidad","racionalizado","radiante","raíces","rápidamente","rapidez",
			"rápido","rapto","razón","razonable","razonablemente","reactivar","reafirmación",
			"reafirmamos","realidad","realista","realización","receptivo","recógeme","recogidos",
			"recomendable","recomendación","recomendaciones","recomendado","recomendar","recompensa",
			"recompensadoramente","reconciliación","reconfortante","reconocido","reconocimiento",
			"reconocimientos","récord","rectamente","rectificación","rectificación","rectitud",
			"rectores","recuperación","recuperar","redención","redentor","redimir","reembolso",
			"reemplazable","reestructuración","reestructuración",
			"reestructurado","refina","refinado","reforma","reformado","reformas","refugio","regalo",
			"regiamente","regocijar","regocijo","rejuvenecer","rejuvenecido","relación","relacionados",
			"relaciones","relajado","relajante","relájese","religión","reluciente","relucir","remedio",
			"remisión","remunerado","remunerar","renacimiento","renombre",
			"renovada","renovar","reposo","reputación","resiliencia","resistencia","respaldan",
			"respetable","respeto","respetuosamente","respetuoso","respiro",
			"resplandeciente","resplandor","respondón","responsabilidad","responsablemente","respuesta",
			"restauración","restaurado","resto","resucitado","resultados","reto","retráctil","revelación",
			"reverencia","reverente","reverentemente","revienta","revitalizantes","revive","revoluciona",
			"revolucionará","revolucionario","revolucionó",
			"riqueza","risa","risitas","robustez","robusto","románticamente","romántico","romantizar",
			"rosa","rotundo"
		],
		"s":[
			"saber","sabiamente","sabiduría","saborear","sabroso","sagacidad","sagrado","salud",
			"saludable","saludo","salvación","salvador","sano","santidad","santo",
			"satisface","satisfacer","satisfactoria","satisfactoriamente",
			"satisfactorio","satisfecho","sazonada","seductoramente","segura","seguridad","seguro",
			"selectiva","sello","señas","sencilla","sencillez","sencillo","señorial","sensación",
			"sensacional","sensacionalmente","sensaciones","sensatamente","sensible",
			"serena","serenidad","seriedad","servicio","servir","sí",
			"significado","significativa","significativo","silencioso","simple","simplifica",
			"simplificación","simplificado","simplificar",
			"sinceramente","sinceridad",
			"sincero","sintonizarse","sistematización","sobreestimación","sobresalido",
			"sobresalientemente","sobreviviente","sofisticado","solícitamente","solícito","sólidamente",
			"solidaridad","solidez","soltura","soñador","sonora","sonriendo",
			"sonriente","sonrisa","sonrisas","soportes","sorprendente","sorprendentemente","sorprendido",
			"sostenibilidad","sostenible","sostenido","suave","suavemente","subsidia","subsidio",
			"subvencionada","subvencionar","suculenta","sueña","suerte","suficiente","suficientemente",
			"sumamente","suntuosa","suntuosamente","suntuosidad","suntuoso","supera","superadas",
			"superado","superando","superar","superioridad","superó",
			"superpotencia","supersónico","supervivencia","suprema","supremacía","supremamente",
			"surrealista","sustantiva","ser"
		],
		"t":[
			"talento","talentos","tapado","tenacidad","tentación","tentador","tentadora",
			"tentadoramente","terapia","tesoro","tiempo","tierra","tipo","tocado","todo",
			"tolerancia","toque","trabajable","trabajado","trabajador",
			"trabajo","tracción","tradición",
			"tradicional","trance","tranquila","tranquilidad","tranquilizar","transformación",
			"transformador","transformar","transparente","trascendental","tremendamente","triunfal",
			"triunfante","triunfo","trivialmente","trofeo","trompeta"
		],
		"u":[
			"unidad","unificación","uniformemente","útil","útiles","utilidad"
		],
		"v":[
			"valentía","válido","valiente","valientemente","valioso",
			"valor","valores","variedad","veneración","venerar","ventaja","ventajas","ventajosamente",
			"ventajoso","veracidad","veraz","verdad","verificable","verificar","versátil","versatilidad",
			"vibrante","victoria","victorioso","vida","vigilancia","vigilante","vigor","vigorizado",
			"vigorizante","vigorizar","virtud","virtuosamente","virtuoso","visible",
			"visionario","vitalidad","vivacidad","vivaz","vivificación",
			"vivir","vivo","voluntad","voluntariamente","voto","vulnerabilidad"
		],
		"x":[
		"xenofilia",
		],
	},
	"negativo":{
		"":[],
	},
};


//http://positivewordsresearch.com/lista-de-palabras-positivas/
//Copyright @ 2013 - 2015 Positive Words Research. All rights reserved.
